console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("girar a la izquierda");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
console.log("mover hacia adelante");
console.log("quitar");
